### ISSUE TITLE
Handle unavailable years

### ISSUE THREAD

**Issue by TaiWilkin** [azavea/fb-gender-survey-dashboard#123]
## Overview

Certain geographies may not be available for all years. In those cases, we should indicate which years are available for the geography, and prevent users from selecting a year if no selected geographies have data available for it. 

### Additional Context

See mockups [here](https://docs.google.com/document/d/1pzBh4glfZKgTPBh0Ir7wAuNBZT4IdqSaUGTg5vjHOzY/edit)

**Comment by rajadain** [comment]
When selecting a year for which data is not available for all regions:

![image](https://user-images.githubusercontent.com/1430060/141331352-21953723-6f93-40ad-88b5-682ce46aaea5.png)

The unavailable region is still mentioned in the Questions page, even though it will be excluded in the final result:

![image](https://user-images.githubusercontent.com/1430060/141331462-ba938ddf-4ead-4a2c-95e0-fe1408997558.png)

Wonder if we can have some sort of disabled / grayed out treatment to indicate that here.
