### ISSUE TITLE
Add a title to the chart canvas

### ISSUE THREAD

**Issue by TaiWilkin** [azavea/fb-gender-survey-dashboard#27]
Add the question text to each chart as a title. 

See [this issue](https://github.com/plouc/nivo/issues/167) for a method which can be used with SVG charts, but that doesn't seem to work on canvas charts. 

Text can be set on canvas charts as axis labels, but there aren't a lot of formatting options, so there doesn't seem to be any way to prevent long text from expanding off of the page. It might be possible to add a short reference to the questions in this way, if adding the full question text proves impossible.

**Comment by mmcfarland** [comment]
If we decide to prioritize this issue we may need to write text directly to the canvas element prior to saving to a PNG. If so, we may want to also geography to the waffle chart, which isn't able to include it on the chart axes like other chart types.
