### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#49]
## Overview

Add Google Tag Manager and make necessary adjustments to allow counting geography and selection checkboxes being clicked. It should be possible to add those two trackers specifically without adding event handlers. Similar consent forms have been added to recent Civic Apps projects.

Here is the full feature request from the scope:

---
Azavea will integrate a message requiring users to opt-in to cookie tracking. No analytics
information will be tracked prior to the user agreeing to that option. We will also link to a
privacy policy or terms of use provided by Facebook. Since no other personally identifiable
information is tracked via user accounts, we do not believe other privacy limitations are
required although Azavea is not an expert on privacy regulations.
- Facebook may need to generate the analytics tracking code in an account they create with
Google Analytics or another third-party service. Facebook will have access to all analytics
information in that account.
- Azavea will use Google Tag Manager or another third-party service to track two specific metrics:
  - How often specific countries are selected by users
  - How often specific questions are selected by users

**Comment by dboyer** [comment]
We will not be implementing any cookie opt-out/privacy banner.

**Comment by dboyer** [comment]
The ID is:

G-DWE5K1N00D

**Comment by dboyer** [comment]
We will need to coordinate a screen share time with Samhir as he has the login for the account.
