### ISSUE TITLE
Update copy throughout site

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#62]
# Overview

Excluding FAQ and About Us which are handled in distinct cards.

Check the following docs for the final list, but include header and footer and general page content.

https://docs.google.com/spreadsheets/d/1jeDH5uchMijCl4gXCEs-LHNEmVcAx-mYhoIb1S8XVC0/edit#gid=0
https://docs.google.com/document/d/1ygYvYoe9MdTPn_2WkJCLhKUWJE2yiGMXWqmmyKXWLXI/edit#

**Comment by dboyer** [comment]
About/FAQ/Home page text ready at https://docs.google.com/document/d/1ygYvYoe9MdTPn_2WkJCLhKUWJE2yiGMXWqmmyKXWLXI/edit#

**Comment by TaiWilkin** [comment]
Footer content update has been moved to #54. 

This issue will address feedback items #15, #16, #18, #25,  and #31 in the feedback document. The header style will also be updated to match the most recent mockups.

**Comment by alexelash** [comment]
FYI I'm folding 35 & 36 into the style pass.
