### ISSUE TITLE
Small features

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#64]
# Overview

Small features, included points allocated for feedback.

## Map image
Insert provided image to geography selector page, as shown in the visual design

https://drive.google.com/file/d/175MbkM6Vj1YgeFis8-VLg8258R8imhOW/view?usp=sharing

![image.png](https://images.zenhubusercontent.com/5c9cd73ac9f52949557690d9/3f2411b3-93f5-415b-87c1-6dd5ee4770ce)

# Stacked charts
- Format values as %, use fixed 100 axis.

# Groups on Viz
- On the visualization page, wrap each category section of charts into an accordion that can have multiple items open at once. Default to all open.

# Percentage and Stack Types
- Bar charts do not make it clear what the unit of analysis is. Suggest either or both adding language to the text above the chart that says, "Percent who answered yes" rather than just "Answered yes" as someone might think the figure is presenting number of respondents not percentage. To be extra clear it would then be good to have an indication of the unit of analysis on the X-axis ("percent providing given response"). This comment applies to all charts where unit of analysis is percent.

**Comment by dboyer** [comment]
Use this image instead. Can recrop it from the original image earlier in this issue if the dimensions are off.

![gender-survey-countries](https://user-images.githubusercontent.com/516764/105070439-4a47c380-5a51-11eb-9fb8-0994722edd62.png)

**Comment by mmcfarland** [comment]
Another small tweak would be to add placeholder text for our search boxes. I thought we might have done this already, so if they were removed intentionally, I'm not asking for them to be brought back. However, something like "Filter countries" and "Filter Questions" seem appropriate.

![image.png](https://images.zenhubusercontent.com/5c9cd73ac9f52949557690d9/471b16bf-05a4-476b-8fa4-39544af0c013)

**Comment by alexelash** [comment]
@mmcfarland That was an intentional removal, yep!
