### ISSUE TITLE
Set specific colors for chart rendering

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#65]
# Overview 

Confirm what the most recent color sets per chart-value are and configure the rendering to use them.

**Comment by alexelash** [comment]
@TaiWilkin @mmcfarland These are finalized now: https://share.goabstract.com/08879dd1-30d8-44af-bbfb-40f22288d5cc?collectionLayerId=4808347d-0358-4705-b0a9-0c159c83af2b&mode=design

**Comment by TaiWilkin** [comment]
Finalized colors:

Grouped Charts and Waffle Charts: (Follows current design)

- Women: rgb(54, 17, 52); (Dark Red)
- Men: rgb(220, 56, 70); (Red)
- Total: rgb(243, 164, 142); (Pink)


Stacked Charts: (Differs from current design)
- Disagree: rgb(54, 17, 52); (Dark Red)
- Neutral: rgb(243, 164, 142); (Pink)
- Agree: rgb(220, 56, 70); (Red)
