### ISSUE TITLE
Add notification bar for survey

### ISSUE THREAD

**Issue by mmcfarland** [azavea/fb-gender-survey-dashboard#69]
## Overview

After a delay of 2 minutes, show a notification bar above the header which asks the user to provide feedback via a link. Add a close button which persists the setting, so that the bar is not shown on subsequent visits to the site.

The text hasn't been specified, but we can use placeholder "We'd love to hear what you think, add your feedback here"

We can use a placeholder link that opens a new tab that will eventually be a SurveyMonkey form.

**Comment by mmcfarland** [comment]
@alexelash This was an additional feature requested by the client, though I don't think the banner is a hard requirement, if you'd prefer a different type of notification container.

**Comment by dboyer** [comment]
Desired behavior - The notification for the survey should display 30 seconds after the user visits the visualization page. 

Survey link - https://docs.google.com/forms/d/e/1FAIpQLSfWXehbiAY_7E02FJXDIjbL4dbJSDtQ7DRE_e9uKNeADFmEKw/viewform

Text - "You're invited to take a 30-second survey about this dataset - click here to begin!"

**Comment by dboyer** [comment]
@alexelash Facebook asked for a brighter color behind the survey notification in order to draw people's attention. Perhaps one of the reds used elsewhere on the site.
