### ISSUE TITLE
Questions search: Search prompts a console error & no visual feedback for results

### ISSUE THREAD

**Issue by alexelash** [azavea/fb-gender-survey-dashboard#73]
## Overview
This is somewhere in between an error report and an enhancement. Happy to split these out if they're less related than I think they might be.

This is the error:
<img width="1679" alt="Screen Shot 2021-01-21 at 12 02 37 PM" src="https://user-images.githubusercontent.com/5672295/105321311-b9075700-5be0-11eb-8bd8-00765c304367.png">

The enhancement would be that I thought the search bar wasn't working because nothing happened on the frontend. I would have expected the accordions to open when there are results (each accordion has 1 hit):
<img width="1170" alt="Screen Shot 2021-01-21 at 12 02 56 PM" src="https://user-images.githubusercontent.com/5672295/105322068-c113c680-5be1-11eb-935f-28aa6b16c752.png">

### Expected Behavior
- User searches using the search bar.
- All accordions open so the user can see that something has changed.

### Actual Behavior
- User searches using the search bar.
- An error appears in the console.
- If there are NO results, then text appears saying so.
- If there are results, then nothing happens. The user needs to open accordions (or already have opened them) to see anything.

### Steps to Reproduce
- On homepage, select some regions or countries and hit Next.
- Search for "yes"
- Nothing happens on the frontend. 
- Open accordions to see that there is content inside that matches "yes".

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Optional. Add any other context about the problem here.

**Comment by TaiWilkin** [comment]
@alexelash Do we want the accordion to open if it's closed and the user selects the accordion checkbox? Or is it better to only 'auto-open' in response to a query?
